### ISSUE TITLE
Allow videos where user is in frame for at least 3 seconds

### ISSUE THREAD

**Issue by sebastian-paez** [tristanpank/gait-analysis-swe#78]
Currently, the pose detection will not work correctly if the user is not detected in a single frame throughout the video. We should change this and account for videos that may not show the user for a short duration such as at the start or end of the video. 

We should also add a check to make sure the user is visible in the video for at minimum 3 seconds to ensure that there is enough footage for the form analysis to be meaningful. If the video is invalid in either way, the user should be shown an error telling them so.

**Comment by DiegoCarra** [comment]
If we have a minimum it should be half a second, that still is a whole step cycle at even at 120 spm.
